---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.name }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  members: {{ .Values.replicaCount }}
  type: ReplicaSet
  version: {{ .Values.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.auth.username }}
      db: admin
      passwordSecretRef:
        name: {{ .Values.name }}-mongodb-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: {{ .Values.auth.scramCredentialsSecretName }}
  additionalMongodConfig:
    {{- toYaml .Values.additionalMongodConfig | nindent 4 }}
  statefulSet:
    spec:
      {{- with .Values.serviceName }}
      serviceName: {{ . }}
      {{- end }}
      template:
        {{- if or .Values.podAnnotations .Values.podLabels }}
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podLabels }}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        spec:
          serviceAccountName: {{ .Values.name }}-sa
          {{- with .Values.priorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
          {{- with .Values.terminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ . }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: mongod
              {{- with .Values.mongod.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.mongod.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            - name: mongodb-agent
              {{- with .Values.mongodbAgent.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.mongodbAgent.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: {{ .Values.persistent.accessModes }}
            resources:
              requests:
                storage: {{ .Values.persistent.size }}
            storageClassName: {{ .Values.persistent.storageClass }}
        - metadata:
            name: logs-volume
          spec:
            accessModes: {{ .Values.log.persistent.accessModes }}
            resources:
              requests:
                storage: {{ .Values.log.persistent.size }}
            storageClassName: {{ .Values.log.persistent.storageClass }}
