
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-sa-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-sa
roleRef:
  kind: Role
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
