{{- include "clamav.validateFreshclam" . -}}
{{- if include "clamav.freshclamSecretEnabled" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clamav.freshclamConfigSecretName" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
type: Opaque
stringData:
  freshclam.conf: |
    {{- include "clamav.freshclamConfig" . | nindent 4 }}
{{- end }}
