---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.service.port | quote }}
  {{- if .Values.grpcService.enabled }}
  GRPC_PORT: {{ .Values.grpcService.port | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
