{{- if .Values.dockerConfig.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ $fullName }}-dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig.data }}
{{- end }}
