{{- $fullName := include "backend.fullname" . -}}
{{- range $v:= .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-{{ $v.refSecretName }}-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .clusterStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $fullName }}-{{ $v.refSecretName }}-secret
  data:
    {{- range $key, $value := $v.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $v.refSecretName }}
        {{- if $v.isUseProperty }}
        property: {{ $value }}
        {{- end }}
    {{- end }}
---
{{- end }}
