{{- $services := (include "backend.services" . | fromYaml).items }}
{{- range $svc := $services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  labels:
    {{- include "backend.labels" $ | nindent 4 }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  ports:
    {{- range $port := $svc.ports }}
    - port: {{ $port.port }}
      targetPort: {{ default $port.port $port.targetPort }}
      protocol: {{ default "TCP" $port.protocol }}
      name: {{ $port.name }}
      {{- with $port.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- with $port.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "backend.selectorLabels" $ | nindent 4 }}
{{- end }}
