name: 'mongodb'
replicaCount: 3
version: '8.2.0'

auth:
  password: ''
  username: 'root'

persistent:
  storageClass: ''
  size: '3Gi'

log:
  persistent:
    storageClass: ''
    size: '1Gi'

mongod:
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 256Mi

mongodbAgent:
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 256Mi
    # requests:
    #   cpu: 50m
    #   memory: 128Mi