{{- if .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.fullname" . }}-secret
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
  username: {{ .Values.auth.username | quote }}
{{- end }}
