{{- range $index, $instrumentation := .Values.instrumentations }}
{{- if ne $instrumentation.enabled false }}
{{- $defaultName := printf "%s-instrumentation" (include "name" $) }}
{{- if $index }}
{{- $defaultName = printf "%s-instrumentation-%d" (include "name" $) (int $index) }}
{{- end }}
{{- $namespaces := $instrumentation.namespaces | default (list $instrumentation.namespace) }}
{{- range $namespace := $namespaces }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ default $defaultName $instrumentation.name | trunc 63 | trimSuffix "-" }}
  {{- with $namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with $instrumentation.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $instrumentation.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  exporter:
    endpoint: {{ $instrumentation.exporter.endpoint }}
    {{- with $instrumentation.exporter.tls }}
    tls:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with $instrumentation.propagators }}
  propagators:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $instrumentation.sampler }}
  sampler:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $instrumentation.resource }}
  resource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $instrumentation.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- range $language := list "java" "nodejs" "python" "dotnet" "go" "apacheHttpd" "nginx" }}
  {{- with (index $instrumentation $language) }}
  {{ $language }}:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
