{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "name" .)) .Values.secret.name }}
  {{- with .Values.collector.namespace }}
  namespace: {{ . }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
