apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL
type: application
version: 0.0.1
dependencies:
  - name: cluster
    alias: cnpg
    version: 0.3.1
    repository: 'https://cloudnative-pg.io/charts/'
